import type { Supplier } from "./types";

export const SEED_SUPPLIERS: Supplier[] = [
  {
    id: "sup-1",
    name: "Dhaka Footwear Traders",
    contactPerson: "Mr. Jamal Uddin",
    phone: "01711000111",
    email: "jamal@dhakafootwear.com",
    status: "active",
    archived: false,
    address: "Shop 45, Chowk Bazar",
    city: "Dhaka",
    notes: "Primary sneaker supplier.",
    paymentTerms: "15 days",
    currency: "BDT",
    openingBalance: 0,
    createdAt: "2026-04-10T10:00:00.000Z",
  },
  {
    id: "sup-2",
    name: "Chattogram Leather Works",
    contactPerson: "Ms. Farida Yasmin",
    phone: "01822000222",
    email: "farida@ctgleather.com",
    status: "active",
    archived: false,
    address: "Agrabad Commercial Area",
    city: "Chattogram",
    notes: "",
    paymentTerms: "Cash",
    currency: "BDT",
    openingBalance: 15000,
    createdAt: "2026-05-02T10:00:00.000Z",
  },
  {
    id: "sup-3",
    name: "Global Sports Import Ltd.",
    contactPerson: "Mr. Rezaul Karim",
    phone: "01933000333",
    email: "rezaul@globalsportsbd.com",
    status: "inactive",
    archived: false,
    address: "Gulshan Avenue",
    city: "Dhaka",
    notes: "Paused since last season — pricing renegotiation pending.",
    paymentTerms: "30 days",
    currency: "USD",
    openingBalance: 0,
    createdAt: "2026-02-18T10:00:00.000Z",
  },
];
